export enum ActionTypes {
    CHANGE_EVENT = "CHANGE_EVENT",

    CHANGE_START_DAY = "CHANGE_START_DAY",
    CHANGE_END_DAY = "CHANGE_END_DAY",

    CHANGE_INTERVIEW_TIME = "CHANGE_INTERVIEW_TIME",

    CHANGE_VIEW_TYPE = "CHANGE_VIEW_TYPE",

    ADD_RECRUITER_EVENT = "ADD_RECRUITER_EVENT",
    REMOVE_RECRUITER_EVENT = "REMOVE_RECRUITER_EVENT",
    EDIT_RECRUITER_EVENT = "EDIT_RECRUITER_EVENT",

    RESIZE = "RESIZE",
}
