export enum ActionTypes {
    GET_ROLE_REQUEST = "GET_ROLE_REQUEST",
    GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS",
    GET_ROLE_FAILURE = "GET_ROLE_FAILURE",

    GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST",
    GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE",

    CHANGE_EVENT_REQUEST = "CHANGE_EVENT_REQUEST",
    CHANGE_EVENT_SUCCESS = "CHANGE_EVENT_SUCCESS",
    CHANGE_EVENT_FAILURE = "CHANGE_EVENT_FAILURE",

    CHANGE_START_DAY = "CHANGE_START_DAY",
    CHANGE_END_DAY = "CHANGE_END_DAY",

    GET_WORK_DAY_REQUEST = "GET_WORK_DAY_REQUEST",
    GET_WORK_DAY_SUCCESS = "GET_WORK_DAY_SUCCESS",
    GET_WORK_DAY_FAILURE = "GET_WORK_DAY_FAILURE",

    CHANGE_WORK_DAY_REQUEST = "CHANGE_WORK_DAY_REQUEST",
    CHANGE_WORK_DAY_SUCCESS = "CHANGE_WORK_DAY_SUCCESS",
    CHANGE_WORK_DAY_FAILURE = "CHANGE_WORK_DAY_FAILURE",

    GET_INTERVIEW_TIME_REQUEST = "GET_INTERVIEW_TIME_REQUEST",
    GET_INTERVIEW_TIME_SUCCESS = "GET_INTERVIEW_TIME_SUCCESS",
    GET_INTERVIEW_TIME_FAILURE = "GET_INTERVIEW_TIME_FAILURE",

    CHANGE_INTERVIEW_TIME_REQUEST = "CHANGE_INTERVIEW_TIME_REQUEST",
    CHANGE_INTERVIEW_TIME_SUCCESS = "CHANGE_INTERVIEW_TIME_SUCCESS",
    CHANGE_INTERVIEW_TIME_FAILURE = "CHANGE_INTERVIEW_TIME_FAILURE",

    GET_RECRUITERS_REQUEST = "GET_RECRUITERS_REQUEST",
    GET_RECRUITERS_SUCCESS = "GET_RECRUITERS_SUCCESS",
    GET_RECRUITERS_FAILURE = "GET_RECRUITERS_FAILURE",

    FILTER_RECRUITERS = "FILTER_RECRUITERS",

    ADD_RECRUITER_EVENT_REQUEST = "ADD_RECRUITER_EVENT_REQUEST",
    ADD_RECRUITER_EVENT_SUCCESS = "ADD_RECRUITER_EVENT_SUCCESS",
    ADD_RECRUITER_EVENT_FAILURE = "ADD_RECRUITER_EVENT_FAILURE",

    REMOVE_RECRUITER_EVENT_REQUEST = "REMOVE_RECRUITER_EVENT_REQUEST",
    REMOVE_RECRUITER_EVENT_SUCCESS = "REMOVE_RECRUITER_EVENT_SUCCESS",
    REMOVE_RECRUITER_EVENT_FAILURE = "REMOVE_RECRUITER_EVENT_FAILURE",

    EDIT_RECRUITER_EVENT_REQUEST = "EDIT_RECRUITER_EVENT_REQUEST",
    EDIT_RECRUITER_EVENT_SUCCESS = "EDIT_RECRUITER_EVENT_SUCCESS",
    EDIT_RECRUITER_EVENT_FAILURE = "EDIT_RECRUITER_EVENT_FAILURE",

    RESIZE = "RESIZE",
    CHANGE_VIEW_TYPE = "CHANGE_VIEW_TYPE",
    CLOSE_ERROR_WINDOW = "CLOSE_ERROR_WINDOW",
}
