export enum ActionTypes {
    GET_INFORMATION_REQUEST = "GET_INFORMATION_REQUEST",
    GET_INFORMATION_SUCCESS = "GET_INFORMATION_SUCCESS",
    GET_INFORMATION_FAILURE = "GET_INFORMATION_FAILURE",

    GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST",
    GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE",

    CHANGE_WORK_TIME_REQUEST = "CHANGE_WORK_TIME_REQUEST",
    CHANGE_WORK_TIME_SUCCESS = "CHANGE_WORK_TIME_SUCCESS",
    CHANGE_WORK_TIME_FAILURE = "CHANGE_WORK_TIME_FAILURE",

    CHANGE_INTERVIEW_TIME_REQUEST = "CHANGE_INTERVIEW_TIME_REQUEST",
    CHANGE_INTERVIEW_TIME_SUCCESS = "CHANGE_INTERVIEW_TIME_SUCCESS",
    CHANGE_INTERVIEW_TIME_FAILURE = "CHANGE_INTERVIEW_TIME_FAILURE",

    ADD_RECRUITER_EVENT_REQUEST = "ADD_RECRUITER_EVENT_REQUEST",
    ADD_RECRUITER_EVENT_SUCCESS = "ADD_RECRUITER_EVENT_SUCCESS",
    ADD_RECRUITER_EVENT_FAILURE = "ADD_RECRUITER_EVENT_FAILURE",

    REMOVE_RECRUITER_EVENT_REQUEST = "REMOVE_RECRUITER_EVENT_REQUEST",
    REMOVE_RECRUITER_EVENT_SUCCESS = "REMOVE_RECRUITER_EVENT_SUCCESS",
    REMOVE_RECRUITER_EVENT_FAILURE = "REMOVE_RECRUITER_EVENT_FAILURE",

    EDIT_RECRUITER_EVENT_REQUEST = "EDIT_RECRUITER_EVENT_REQUEST",
    EDIT_RECRUITER_EVENT_SUCCESS = "EDIT_RECRUITER_EVENT_SUCCESS",
    EDIT_RECRUITER_EVENT_FAILURE = "EDIT_RECRUITER_EVENT_FAILURE",

    SIGN_UP_VOLUNTEER_REQUEST = "SIGN_UP_VOLUNTEER_REQUEST",
    SIGN_UP_VOLUNTEER_SUCCESS = "SIGN_UP_VOLUNTEER_SUCCESS",
    SIGN_UP_VOLUNTEER_FAILURE = "SIGN_UP_VOLUNTEER_FAILURE",

    SET_ROLE = "SET_ROLE",
    SET_VIEW = "SET_VIEW",
    RESIZE = "RESIZE",
    CHANGE_EVENT = "CHANGE_EVENT",
    CHANGE_VIEW_TYPE = "CHANGE_VIEW_TYPE",
    CHANGE_CALENDAR_VIEW_TYPE = "CHANGE_CALENDAR_VIEW_TYPE",
    CHANGE_DATE = "CHANGE_DATE",
    CLOSE_ERROR_WINDOW = "CLOSE_ERROR_WINDOW",
}
